[tools]
age = "latest"
bat = "latest"
chezmoi = "latest"
delta = "latest"
difftastic = { version = "latest", exe = "difft" }
fd = "latest"
fzf = "latest"
"github:micro-editor/micro" = "latest"
jq = "latest"
lazygit = "latest"
# neovim = "latest"
node = "lts"
"npm:czg" = "latest"
"npm:prettier" = "latest"
python = "3.13"
ripgrep = "latest"
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
taplo = "latest"
# tmux = "latest"
uv = "latest"
yazi = "latest"
# zellij = "latest"
zoxide = "latest"

[settings]
disable_backends = ["asdf"]
