[tools]
age = "latest"
"aqua:micro-editor/micro" = "latest"
bat = "latest"
chezmoi = "latest"
delta = "latest"
difftastic = { version = "latest", exe = "difft" }
fd = "latest"
fzf = "latest"
jq = "latest"
lazygit = "latest"
lua-language-server = "latest"
neovim = "0.11.6"
node = "lts"
"npm:czg" = "latest"
"npm:bash-language-server" = "latest"
"npm:basedpyright" = "latest"
# "npm:@openai/codex" = "latest"
# "npm:opencode-ai" = "latest"
"npm:prettier" = "latest"
python = "3.13"
ripgrep = "latest"
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
stylua = "latest"
taplo = "latest"
# tmux = "latest"
uv = "latest"
yazi = "latest"
# zellij = "latest"
zoxide = "latest"

[settings]
disable_backends = ["asdf"]
