[tools]
age = "latest"
bat = "latest"
chezmoi = "latest"
delta = "latest"
difftastic = { version = "latest", exe = "difft" }
fd = "latest"
fzf = "latest"
"github:micro-editor/micro" = "latest"
jq = "latest"
lazygit = "latest"
lua-language-server = "latest"
neovim = "0.11.5"
node = "lts"
"npm:czg" = "latest"
"npm:opencode-ai" = "latest"
"npm:prettier" = "latest"
"npm:pyright" = "latest"
# "npm:tree-sitter-cli" = "latest"
python = "3.13"
ripgrep = "latest"
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
stylua = "latest"
taplo = "latest"
tmux = "3.6a"
uv = "latest"
yazi = "latest"
# zellij = "latest"
zoxide = "latest"

[settings]
disable_backends = ["asdf"]
